#!/bin/bash

exec xautolock -detectsleep -time 10 -locker slock -notify 30 -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" &

exec xidlehook --not-when-fullscreen --timer 1200 "loginctl suspend"
